version: '3'

services:
  postgres:
    image: postgres:12.2
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - plano-db-vol:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=plano-postgres-db"

  adminer:
    image: adminer:4.7
    ports:
      - 8080:8080
      
volumes:
    plano-db-vol: ~
